version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: npm install && npm test
  deploy:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: npm install && npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: 'us‑east‑1'
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: 's3://ci-cdtaller'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: build
          to: 's3://ci-cdtaller'
workflows:
  test_build_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test